default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: rent_properties_development

test:
  <<: *default
  database: rent_properties_test

production:
  <<: *default
  database: rent_properties_production
  username: rent_properties
  password: <%= ENV["RENT_PROPERTIES_DATABASE_PASSWORD"] %>
